name: Deploy to CloudPanel

on:
  push:
    branches:
      - main  # Change to your deployment branch

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to CloudPanel VPS
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up SSH Key
      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      # Step 3: Deploy to CloudPanel VPS
      - name: Deploy Project
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
          "cd /home/devzet-demo/htdocs/demo.devzet.com && \
          git pull origin main && \
          composer install --no-dev --optimize-autoloader && \
          php artisan migrate --force && \
          sudo systemctl restart nginx"
