name: Deploy to CloudPanel

on:
  push:
    branches:
      - main  # Change to your deployment branch

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Push changes
        run: |
          git config --global user.name "imtiaz0212"
          git config --global user.email "imtiaz0212@gmail.com"
          git remote set-url origin git@github.com:imtiaz0212/laravel-git-action.git
          git add .
          git commit -m "Automated commit from GitHub Actions"
          git push origin main
